# Generated by Django 5.2.16 on 2026-07-31 18:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MovimientoCuenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('cuenta', models.CharField(default='principal', max_length=120)),
                ('tipo', models.CharField(choices=[('cargo', 'Cargo'), ('abono', 'Abono')], max_length=10)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=14)),
                ('descripcion', models.CharField(blank=True, max_length=255)),
                ('referencia', models.CharField(blank=True, max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-fecha', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PeriodoTributario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.DateField(help_text='Día 1 del mes.', unique=True)),
                ('total_neto', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('iva_debito', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('iva_credito', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('iva_a_pagar', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('ppm', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('notas', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'período tributario',
                'verbose_name_plural': 'períodos tributarios',
                'ordering': ['-periodo'],
            },
        ),
        migrations.CreateModel(
            name='DocumentoSII',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.DateField(help_text='Usar el día 1 del mes del período.')),
                ('titulo', models.CharField(max_length=200)),
                ('archivo', models.FileField(upload_to='sii/')),
                ('notas', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'documento SII',
                'verbose_name_plural': 'documentos SII',
                'ordering': ['-periodo', '-created_at'],
            },
        ),
    ]
