# Generated by Django 5.2.16 on 2026-08-03 03:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0001_initial'),
        ('presupuestos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CuentaBancaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('banco', models.CharField(max_length=120)),
                ('numero', models.CharField(blank=True, max_length=64)),
            ],
            options={
                'verbose_name': 'cuenta bancaria',
                'verbose_name_plural': 'cuentas bancarias',
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='movimientocuenta',
            name='factura',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos', to='presupuestos.facturaboleta'),
        ),
        migrations.AddField(
            model_name='movimientocuenta',
            name='cuenta_bancaria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos', to='finanzas.cuentabancaria'),
        ),
    ]
