# Generated by Django 5.2.16 on 2026-07-31 18:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoProyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('color', models.CharField(default='#0066FF', max_length=20)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'estado de proyecto',
                'verbose_name_plural': 'estados de proyecto',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('clientes', models.ManyToManyField(blank=True, related_name='proyectos', to='clientes.cliente')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proyectos_creados', to=settings.AUTH_USER_MODEL)),
                ('equipo', models.ManyToManyField(blank=True, related_name='proyectos_equipo', to=settings.AUTH_USER_MODEL)),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='proyectos', to='proyectos.estadoproyecto')),
            ],
            options={
                'verbose_name': 'proyecto',
                'verbose_name_plural': 'proyectos',
                'ordering': ['-updated_at'],
                'permissions': [('view_all_proyectos', 'Puede ver todos los proyectos')],
            },
        ),
        migrations.CreateModel(
            name='TimelineEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('estado', 'Cambio de estado'), ('documento', 'Documento'), ('incidencia', 'Incidencia'), ('presupuesto', 'Presupuesto'), ('activo', 'Activo'), ('otro', 'Otro')], default='otro', max_length=32)),
                ('titulo', models.CharField(max_length=255)),
                ('detalle', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline', to='proyectos.proyecto')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
