# Generated by Django 5.2.16 on 2026-08-03 03:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

# (slug, visible_cliente) — borrador False; alineado con 0002 seed
VISIBLE_SEED = {
    'borrador': False,
    'creado': False,
    'generando-ppto': False,
    'esperando-confirmacion-equipo': False,
    'esperando-aceptacion-cliente': True,
    'instalacion-en-progreso': True,
    'finalizado': True,
    'con-incidencia': True,
    'esperando-incidencia': True,
}


def seed_visible_and_codigo(apps, schema_editor):
    Estado = apps.get_model('proyectos', 'EstadoProyecto')
    for slug, visible in VISIBLE_SEED.items():
        Estado.objects.filter(slug=slug).update(visible_cliente=visible)

    Proyecto = apps.get_model('proyectos', 'Proyecto')
    for p in Proyecto.objects.filter(models.Q(codigo='') | models.Q(codigo__isnull=True)).order_by('pk'):
        p.codigo = str(p.pk)
        p.save(update_fields=['codigo'])


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0002_seed_estados'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='estadoproyecto',
            name='visible_cliente',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='codigo',
            field=models.CharField(blank=True, default='', max_length=32),
            preserve_default=False,
        ),
        migrations.RunPython(seed_visible_and_codigo, noop),
        migrations.AlterField(
            model_name='proyecto',
            name='codigo',
            field=models.CharField(blank=True, max_length=32, unique=True),
        ),
        migrations.CreateModel(
            name='ComentarioProyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comentarios_proyecto', to=settings.AUTH_USER_MODEL)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='proyectos.proyecto')),
            ],
            options={
                'verbose_name': 'comentario de proyecto',
                'verbose_name_plural': 'comentarios de proyecto',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='TimelineConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auto_estado', models.BooleanField(default=True)),
                ('auto_documento', models.BooleanField(default=True)),
                ('auto_incidencia', models.BooleanField(default=True)),
                ('auto_presupuesto', models.BooleanField(default=True)),
                ('auto_activo', models.BooleanField(default=True)),
                ('visible_cliente_estado', models.BooleanField(default=True)),
                ('visible_cliente_documento', models.BooleanField(default=False)),
                ('visible_cliente_incidencia', models.BooleanField(default=False)),
                ('visible_cliente_presupuesto', models.BooleanField(default=False)),
                ('visible_cliente_activo', models.BooleanField(default=False)),
                ('proyecto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='timeline_config', to='proyectos.proyecto')),
            ],
            options={
                'verbose_name': 'configuración de timeline',
                'verbose_name_plural': 'configuraciones de timeline',
            },
        ),
    ]
