# Generated by Django 5.2.12 on 2026-08-06 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0004_seed_visible_codigo'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='progreso',
            field=models.PositiveSmallIntegerField(default=0, help_text='0–100'),
        ),
    ]
