# Generated by Django 5.2.16 on 2026-08-03 03:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendario', '0001_initial'),
        ('proyectos', '0003_codigo_comentarios_timeline_visible'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='tipo',
            field=models.CharField(choices=[('reunion', 'Reunión'), ('visita', 'Visita'), ('otro', 'Otro')], default='otro', max_length=20),
        ),
        migrations.AddField(
            model_name='evento',
            name='ubicacion',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.CreateModel(
            name='CapaCalendario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('color', models.CharField(default='#3498db', max_length=20)),
                ('visible', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capas_calendario', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'capa de calendario',
                'verbose_name_plural': 'capas de calendario',
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='evento',
            name='capa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos', to='calendario.capacalendario'),
        ),
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('prioridad', models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta')], default='media', max_length=10)),
                ('deadline', models.DateField()),
                ('completada', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asignados', models.ManyToManyField(blank=True, related_name='tareas_asignadas', to=settings.AUTH_USER_MODEL)),
                ('capa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tareas', to='calendario.capacalendario')),
                ('creador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tareas_creadas', to=settings.AUTH_USER_MODEL)),
                ('proyecto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tareas', to='proyectos.proyecto')),
            ],
            options={
                'ordering': ['deadline', 'prioridad'],
            },
        ),
    ]
