# Generated by Django 5.2.16 on 2026-08-03 03:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'categoría de documento',
                'verbose_name_plural': 'categorías de documento',
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='documento',
            name='solo_admin',
            field=models.BooleanField(default=False, help_text='Si True, solo administradores del sistema pueden acceder.'),
        ),
        migrations.AddField(
            model_name='documento',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos', to='documentos.categoriadocumento'),
        ),
    ]
