# Generated by Django 5.2.16 on 2026-08-03 03:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidencias', '0002_incidencia_activos_incidencia_causas_and_more'),
        ('presupuestos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='presupuesto',
            name='incidencia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='presupuestos', to='incidencias.incidencia'),
        ),
        migrations.AddField(
            model_name='presupuesto',
            name='visita_mantenimiento_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='presupuestoitem',
            name='costo_insumo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='presupuestoitem',
            name='incidencia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='presupuesto_items', to='incidencias.incidencia'),
        ),
        migrations.AddField(
            model_name='presupuestoitem',
            name='neto_unidad',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='presupuestoitem',
            name='pct_desinstalacion',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='presupuestoitem',
            name='pct_ferreteria',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='presupuestoitem',
            name='pct_flete',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='presupuestoitem',
            name='pct_gg',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='presupuestoitem',
            name='pct_instalacion',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='presupuestoitem',
            name='pct_maquila',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='presupuestoitem',
            name='pct_utilidad',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='presupuestoitem',
            name='referencia',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='presupuestoitem',
            name='tipo',
            field=models.CharField(choices=[('material', 'Material'), ('servicio', 'Servicio')], default='material', max_length=20),
        ),
        migrations.AddField(
            model_name='presupuestoitem',
            name='utilidad_manual',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='presupuestoitem',
            name='visita_mantenimiento_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='presupuestoitem',
            name='descripcion',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
