# Generated by Django 5.2.16 on 2026-08-06 20:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presupuestos', '0002_presupuesto_incidencia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gasto',
            name='factura',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='gastos', to='presupuestos.facturaboleta', verbose_name='factura / boleta'),
        ),
    ]
