# Generated by Django 5.2.12 on 2026-08-06 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presupuestos', '0003_gasto_factura_vinculo'),
    ]

    operations = [
        migrations.AddField(
            model_name='presupuesto',
            name='descuento_pct',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='presupuesto',
            name='generalidades',
            field=models.TextField(blank=True, default='DESPACHO DE PRODUCTOS A LA OBRA\nINSTALACION DE PRODUCTOS\nGARANTIA DE 12 MESES A PARTIR DE LA FECHA DE ENTREGA (SUJETO A TERMINOS Y CONDICIONES)\nTIEMPO DE FABRICACION 4 DIAS.\nTIEMPO DE EJECUCION 10 DIAS\nANTICIPO 50% PARA EL COMIENZO DE LA OBRA - 50% AL FINALIZAR LA OBRA'),
        ),
        migrations.AddField(
            model_name='presupuestoitem',
            name='caracteristicas',
            field=models.CharField(blank=True, max_length=255, verbose_name='características'),
        ),
        migrations.AddField(
            model_name='presupuestoitem',
            name='tipologia',
            field=models.CharField(blank=True, max_length=120, verbose_name='tipología'),
        ),
        migrations.AddField(
            model_name='presupuestoitem',
            name='ubicacion',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
