# Generated by Django 5.2.16 on 2026-08-06 21:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presupuestos', '0004_cotizacion_ui_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='facturaboleta',
            name='proveedor',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='gasto',
            name='pagado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gastos_pagados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gasto',
            name='pagado_por_tipo',
            field=models.CharField(choices=[('caja', 'Caja del proyecto'), ('empresa', 'Empresa'), ('usuario', 'Usuario')], default='caja', max_length=20),
        ),
        migrations.AddField(
            model_name='gasto',
            name='tipo',
            field=models.CharField(choices=[('materiales', 'Materiales'), ('transporte', 'Transporte'), ('mano_obra', 'Mano de obra'), ('otros', 'Otros')], default='otros', max_length=20),
        ),
        migrations.AddField(
            model_name='presupuesto',
            name='pct_empresa',
            field=models.DecimalField(decimal_places=2, default=20, max_digits=6),
        ),
        migrations.CreateModel(
            name='PagoEmpleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('porcentaje_pago', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('anticipo', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('quien_anticipo_tipo', models.CharField(choices=[('caja', 'Caja del proyecto'), ('empresa', 'Empresa'), ('usuario', 'Usuario')], default='caja', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos_presupuesto', to=settings.AUTH_USER_MODEL)),
                ('presupuesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos_empleados', to='presupuestos.presupuesto')),
                ('quien_anticipo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='anticipos_pagados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['empleado_id'],
                'unique_together': {('presupuesto', 'empleado')},
            },
        ),
    ]
