# Generated by Django 5.2.16 on 2026-08-03 03:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('proyectos', '0002_seed_estados'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChecklistTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('tipo_servicio', models.SlugField(max_length=120, unique=True)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='ChecklistTemplateItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=500)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='mantenimiento.checklisttemplate')),
            ],
            options={
                'ordering': ['orden', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='VisitaMantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('preventivo', 'Preventivo'), ('correctivo', 'Correctivo')], default='preventivo', max_length=20)),
                ('tipo_servicio', models.SlugField(max_length=120)),
                ('fecha', models.DateField()),
                ('observaciones', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('hecha', 'Hecha'), ('cancelada', 'Cancelada')], default='pendiente', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visitas_mantenimiento_creadas', to=settings.AUTH_USER_MODEL)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitas_mantenimiento', to='proyectos.proyecto')),
            ],
            options={
                'verbose_name': 'visita de mantenimiento',
                'verbose_name_plural': 'visitas de mantenimiento',
                'ordering': ['-fecha', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='VisitaChecklistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=500)),
                ('hecho', models.BooleanField(default=False)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('visita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist', to='mantenimiento.visitamantenimiento')),
            ],
            options={
                'ordering': ['orden', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='FotoVisita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.FileField(upload_to='mantenimiento/fotos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fotos_visita_subidas', to=settings.AUTH_USER_MODEL)),
                ('visita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='mantenimiento.visitamantenimiento')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
