# Generated by Django 5.2.16 on 2026-08-03 03:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0002_categoriaactivo_activo_ip_dominio_activo_tecnico_and_more'),
        ('incidencias', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='incidencia',
            name='activos',
            field=models.ManyToManyField(blank=True, related_name='incidencias', to='activos.activo'),
        ),
        migrations.AddField(
            model_name='incidencia',
            name='causas',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='incidencia',
            name='diagnostico',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='incidencia',
            name='recomendaciones',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='incidencia',
            name='tecnico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidencias_tecnico', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='FotoIncidencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.FileField(upload_to='incidencias/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('incidencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='incidencias.incidencia')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fotos_incidencia', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
