# Generated by Django 5.2.16 on 2026-08-03 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='ciudad',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='cliente',
            name='comuna',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='cliente',
            name='giro',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='cliente',
            name='razon_social',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
