# Generated by Django 5.2.16 on 2026-07-31 18:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('proyectos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('username', models.CharField(blank=True, max_length=120, verbose_name='usuario equipo')),
                ('password', models.CharField(blank=True, max_length=120, verbose_name='contraseña')),
                ('ip', models.CharField(blank=True, max_length=64)),
                ('sn', models.CharField(blank=True, max_length=120, verbose_name='número de serie')),
                ('fecha_instalacion', models.DateField(blank=True, null=True)),
                ('fecha_compra', models.DateField(blank=True, null=True)),
                ('factura_boleta', models.CharField(blank=True, max_length=120, verbose_name='factura/boleta')),
                ('archivo_compra', models.FileField(blank=True, null=True, upload_to='activos/')),
                ('notas', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activos', to='proyectos.proyecto')),
            ],
            options={
                'verbose_name': 'activo',
                'verbose_name_plural': 'activos',
                'ordering': ['-updated_at'],
            },
        ),
    ]
