# Generated by Django 5.2.16 on 2026-08-03 03:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaActivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, unique=True)),
            ],
            options={
                'verbose_name': 'categoría de activo',
                'verbose_name_plural': 'categorías de activo',
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='activo',
            name='ip_dominio',
            field=models.CharField(blank=True, max_length=200, verbose_name='IP / dominio'),
        ),
        migrations.AddField(
            model_name='activo',
            name='tecnico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activos_asignados', to=settings.AUTH_USER_MODEL, verbose_name='técnico'),
        ),
        migrations.AddField(
            model_name='activo',
            name='ubicacion',
            field=models.CharField(blank=True, max_length=200, verbose_name='ubicación'),
        ),
        migrations.AlterField(
            model_name='activo',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activos_creados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='activo',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activos', to='activos.categoriaactivo'),
        ),
    ]
